# Generated by Django 4.1.3 on 2022-11-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
